name: Build Container Components
on:
  workflow_dispatch:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: test version
      run: |
        echo ${{ env.RELEASE_VERSION }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build containers
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        image: chekote/node:14.8.0-alpine
        run: |
          echo "Running Script"
          pwd
          ls -la
          cd ui
          ls -la 
          pwd
          yarn install
          yarn build
      # run: |
      #   export RV=${{ env.RELEASE_VERSION }}
      #   echo "RV set to $RV"
      #   if [ "$RV" == "main" ] || [ "$RV" == "" ] ; then export RV=latest; fi
      #   echo "RV set to $RV"
      #   chmod g+w ./ui
      #   make docker-ui
